### ISSUE TITLE
new API suggested

### ISSUE THREAD

**Issue by lloyd** [vibornoff/node-yajl#2]
I think it should be possible to make an alternative to JSON.parse() that is really compelling.

What if you offered an api that looked like this:

```
var parser = yajl.createParser();
parser.update(data1);
parser.update(data2);
parser.update(data3);
var obj = parser.complete();  
```

This api should be considerably faster than the tree api because you'd be going _directly_ to a javascript object from a utf8 buffer (potentially) skipping the intermediate representation which yajl_tre imposes.  Also it would be awesome when combined with things like the httpclient stuff cause you wouldn't have to save up a full buffer, you could just parse as its available and use the v8 javascript representation as your cache.

thoughts?

**Comment by vibornoff** [comment]
I thought about thing like you suggest and thesis-es are:
- what sort of entities this API would produce? if sax-like events only how it would differ from `yajl.Handle`?
- if it would produce top-level values only and store intermediate data in the javascript representation that in the wast majority cases it would consume more memory compared to buffering;
- despite increased memory consumption this approach could save response time compared to buffering (no full buffer parsing required, only the final chunk);
- it can be usable in hard-realtime systems but the node.js itself doesn't comply to hard-realtime requirements especially because of its garbage collector;
- this sort of API can be usable only when it can beat internal `JSON.parse` performance what itself is a good challenge.

**Comment by vibornoff** [comment]
Nevertheless suggested API looks clean and simple, so I try to implement it at the next weekends.

**Comment by lloyd** [comment]
got curious, so I wrote it: https://github.com/lloyd/node-yajl/commit/85aeeb9933343fe2dad295a9e88f47410791bfad

beating JSON.parse() is f*cking hard.  primarily because object construction (adding properties) is sloooow.

the internal v8 parser does tricks for fast object instantiation.  This line here (just adding properties to javascript objects) accounts for 2/3 of the time:

https://github.com/lloyd/node-yajl/blob/master/src/stream.cc#L28

If we can figure out how to build objects faster from a node extension, then we will have built a json stream parser for node that can parse directly from utf8 buffers (network or file) incrementally and is as fast as native parsing, and uses less memory...  A challenge.

**Comment by lloyd** [comment]
see test_stream.js in that commit for the API and usage...

**Comment by lloyd** [comment]
another note, potentially leaving the object representation in c++ (std::map ?) and writing a wrapper template which lazily creates javascript objects upon access and skips the whole Object::Set mess is the way to go:

http://code.google.com/apis/v8/embed.html#templates
